// Real opportunities data with valid future deadlines (2025-2026)
// Sources: Devpost, MLH, LinkedIn, official scholarship sites

export interface Opportunity {
  id: string;
  type: 'scholarship' | 'internship' | 'hackathon';
  title: string;
  organization: string;
  deadline: string;
  deadlineDate: Date;
  location: string;
  description: string;
  link: string;
  reward: string;
  isRemote?: boolean;
  tags?: string[];
}

export const opportunities: Opportunity[] = [
  // HACKATHONS (10)
  {
    id: 'hack-1',
    type: 'hackathon',
    title: 'MEGA Hackathon 2026',
    organization: 'MEGA Foundation',
    deadline: 'Mar 1, 2026',
    deadlineDate: new Date('2026-03-01'),
    location: 'Online + In-Person',
    description: 'A collaborative hackathon integrating computer science, STEM, economics, and infrastructure aimed at advancing human development.',
    link: 'https://mega-hackathon-2026-students.devpost.com/',
    reward: '$50,000+ in Prizes',
    tags: ['STEM', 'Economics', 'Infrastructure'],
  },
  {
    id: 'hack-2',
    type: 'hackathon',
    title: 'LA Hacks 2026',
    organization: 'UCLA',
    deadline: 'Apr 30, 2026',
    deadlineDate: new Date('2026-04-30'),
    location: 'Los Angeles, USA',
    description: '36-hour annual hackathon at UCLA\'s Pauley Pavilion attracting 1000+ hackers to build impactful technical projects.',
    link: 'https://lahacks.com/',
    reward: '$100,000+ in Prizes',
    tags: ['Innovation', 'Tech', 'Networking'],
  },
  {
    id: 'hack-3',
    type: 'hackathon',
    title: 'Global Hack Week: Beginners',
    organization: 'Major League Hacking (MLH)',
    deadline: 'Aug 14, 2026',
    deadlineDate: new Date('2026-08-14'),
    location: 'Online (Global)',
    description: 'A week-long virtual event designed for beginners to learn, build, and share projects with the global hacker community.',
    link: 'https://ghw.mlh.io/',
    reward: 'Swag + Certificates',
    isRemote: true,
    tags: ['Beginners', 'Learning', 'Community'],
  },
  {
    id: 'hack-4',
    type: 'hackathon',
    title: 'ETHGlobal 2026',
    organization: 'ETHGlobal',
    deadline: 'Jun 15, 2026',
    deadlineDate: new Date('2026-06-15'),
    location: 'Multiple Cities Worldwide',
    description: 'Build the future of Web3 and blockchain applications with mentorship from industry leaders.',
    link: 'https://ethglobal.com/',
    reward: '$150,000 in Prizes',
    tags: ['Web3', 'Blockchain', 'Ethereum'],
  },
  {
    id: 'hack-5',
    type: 'hackathon',
    title: 'HackPue 2026',
    organization: 'MLH Mexico',
    deadline: 'Aug 17, 2026',
    deadlineDate: new Date('2026-08-17'),
    location: 'Puebla, Mexico',
    description: 'Diversity-focused hackathon bringing together developers from Latin America to build innovative solutions.',
    link: 'https://hackpue.com/',
    reward: '$20,000 in Prizes',
    tags: ['Diversity', 'Latin America'],
  },
  {
    id: 'hack-6',
    type: 'hackathon',
    title: 'Deep Learning Day 2026',
    organization: 'Brown University',
    deadline: 'Dec 14, 2026',
    deadlineDate: new Date('2026-12-14'),
    location: 'Providence, RI, USA',
    description: 'University hackathon focused on deep learning and AI applications with hands-on workshops.',
    link: 'https://brown-deep-learning-day-f25.devpost.com/',
    reward: 'Cash Prizes + Mentorship',
    tags: ['AI', 'Deep Learning', 'Research'],
  },
  {
    id: 'hack-7',
    type: 'hackathon',
    title: 'HACK.COMS 2026',
    organization: 'RIT COMS',
    deadline: 'Feb 28, 2026',
    deadlineDate: new Date('2026-02-28'),
    location: 'Rochester, NY, USA',
    description: '25-hour hackathon by Computing Organization for Multicultural Students celebrating underrepresented talent.',
    link: 'https://hack-coms-25.devpost.com/',
    reward: '$15,000 in Prizes',
    tags: ['Diversity', 'Inclusion', 'Students'],
  },
  {
    id: 'hack-8',
    type: 'hackathon',
    title: 'Youth Coders Hack 2026',
    organization: 'Youth Coders Foundation',
    deadline: 'Jul 31, 2026',
    deadlineDate: new Date('2026-07-31'),
    location: 'Online (Global)',
    description: 'Youth-focused hackathon connecting young developers worldwide to learn and build together.',
    link: 'https://youth-coders-hack.devpost.com/',
    reward: '$10,000 in Prizes',
    isRemote: true,
    tags: ['Youth', 'Education', 'Global'],
  },
  {
    id: 'hack-9',
    type: 'hackathon',
    title: 'HackNaija 2026',
    organization: 'Tech Community Nigeria',
    deadline: 'Mar 15, 2026',
    deadlineDate: new Date('2026-03-15'),
    location: 'Lagos, Nigeria + Virtual',
    description: '48-hour hackathon solving local African problems with innovative technology solutions.',
    link: 'https://hacknaija.com',
    reward: '₦10,000,000 Prize Pool',
    tags: ['Africa', 'Social Impact', 'Innovation'],
  },
  {
    id: 'hack-10',
    type: 'hackathon',
    title: 'Status Code 2026',
    organization: 'IIIT Kalyani',
    deadline: 'Aug 24, 2026',
    deadlineDate: new Date('2026-08-24'),
    location: 'West Bengal, India',
    description: 'Student-run hackathon focused on building solutions for real-world challenges in India.',
    link: 'https://hackathon.iiitkalyani.ac.in/',
    reward: '₹500,000 in Prizes',
    tags: ['India', 'Students', 'Innovation'],
  },

  // INTERNSHIPS (10)
  {
    id: 'intern-1',
    type: 'internship',
    title: 'Software Engineering Intern, Summer 2026',
    organization: 'Google',
    deadline: 'Rolling (Apply Early)',
    deadlineDate: new Date('2026-03-31'),
    location: 'Multiple US Locations',
    description: 'Join Google for a 10-12 week internship working on real products that impact billions of users worldwide.',
    link: 'https://www.google.com/about/careers/applications/jobs/results/75808725415142086-software-engineering-intern-bs-summer-2026',
    reward: '$10,000+/month Stipend',
    tags: ['FAANG', 'Software', 'Tech'],
  },
  {
    id: 'intern-2',
    type: 'internship',
    title: 'Software Engineering Intern, 2026',
    organization: 'MongoDB',
    deadline: 'Mar 15, 2026',
    deadlineDate: new Date('2026-03-15'),
    location: 'New York, NY, USA',
    description: 'Work on the world\'s leading modern database platform with a focus on distributed systems.',
    link: 'https://www.linkedin.com/jobs/view/2026-software-engineering-intern-amer-at-mongodb-4300052289',
    reward: 'Competitive Salary + Benefits',
    tags: ['Database', 'Distributed Systems'],
  },
  {
    id: 'intern-3',
    type: 'internship',
    title: 'Software Engineer Intern, Summer 2026',
    organization: 'Cloudflare',
    deadline: 'Feb 28, 2026',
    deadlineDate: new Date('2026-02-28'),
    location: 'Austin, TX, USA',
    description: 'Help build a better Internet by working on Cloudflare\'s edge network and security products.',
    link: 'https://www.linkedin.com/jobs/view/software-engineer-intern-summer-2026-austin-tx-at-cloudflare-4291192756',
    reward: '$8,000+/month Stipend',
    tags: ['Security', 'Edge Computing', 'Networking'],
  },
  {
    id: 'intern-4',
    type: 'internship',
    title: 'Software Engineering Intern (Winter-Spring 2026)',
    organization: 'Gemini',
    deadline: 'Nov 30, 2025',
    deadlineDate: new Date('2025-11-30'),
    location: 'New York, NY, USA',
    description: 'Work on cryptocurrency exchange platform building next-generation financial infrastructure.',
    link: 'https://www.linkedin.com/jobs/view/software-engineering-intern-winter-spring-2026-at-gemini-4309850814',
    reward: 'Competitive Compensation',
    tags: ['Crypto', 'FinTech', 'Trading'],
  },
  {
    id: 'intern-5',
    type: 'internship',
    title: 'Software Engineer Intern, Summer 2026',
    organization: 'Netflix',
    deadline: 'Dec 31, 2025',
    deadlineDate: new Date('2025-12-31'),
    location: 'Los Angeles, CA, USA',
    description: 'Join the world\'s leading streaming entertainment service to build experiences for 300M+ members.',
    link: 'https://www.wayup.com/i-Real-Estate-j-Software-Engineer-Intern-Summer-2026-Netflix-761444730067294/',
    reward: '$10,000+/month Stipend',
    tags: ['Entertainment', 'Streaming', 'Scale'],
  },
  {
    id: 'intern-6',
    type: 'internship',
    title: 'Machine Learning Engineer Intern 2026',
    organization: 'Netflix',
    deadline: 'Dec 31, 2025',
    deadlineDate: new Date('2025-12-31'),
    location: 'Los Angeles, CA, USA',
    description: 'Work on ML systems that power recommendations and content discovery for millions of users.',
    link: 'https://www.linkedin.com/jobs/view/machine-learning-engineer-intern-ms-phd-2026-at-netflix-4312232372',
    reward: '$12,000+/month Stipend',
    tags: ['ML', 'AI', 'Recommendations'],
  },
  {
    id: 'intern-7',
    type: 'internship',
    title: 'Software Engineering Internship 2026',
    organization: 'Apple',
    deadline: 'Rolling (Apply Early)',
    deadlineDate: new Date('2026-04-30'),
    location: 'Cupertino, CA, USA',
    description: 'Bring passion and dedication to extraordinary ideas that become phenomenal Apple products.',
    link: 'https://jobs.apple.com/en-us/details/200606145/software-engineering-internships',
    reward: '$9,500+/month Stipend',
    tags: ['Consumer Tech', 'Hardware', 'iOS'],
  },
  {
    id: 'intern-8',
    type: 'internship',
    title: 'Machine Learning / AI Internship 2026',
    organization: 'Apple',
    deadline: 'Rolling (Apply Early)',
    deadlineDate: new Date('2026-04-30'),
    location: 'Cupertino, CA, USA',
    description: 'Join Apple\'s AIML organization to work on machine learning that powers daily experiences.',
    link: 'https://jobs.apple.com/en-us/details/200606469/machine-learning-ai-internships',
    reward: '$10,000+/month Stipend',
    tags: ['AI', 'ML', 'Siri'],
  },
  {
    id: 'intern-9',
    type: 'internship',
    title: 'Undergraduate Research Internship',
    organization: 'Microsoft Research',
    deadline: 'Feb 28, 2026',
    deadlineDate: new Date('2026-02-28'),
    location: 'Redmond, WA / NYC / New England',
    description: 'Research internship for passionate undergraduates working on cutting-edge computing research.',
    link: 'https://www.microsoft.com/en-us/research/academic-program/undergraduate-research-internship-computing/',
    reward: '$8,000+/month Stipend',
    tags: ['Research', 'Academia', 'Innovation'],
  },
  {
    id: 'intern-10',
    type: 'internship',
    title: 'Software Engineer Intern, Systems & Infrastructure',
    organization: 'Meta',
    deadline: 'Mar 31, 2026',
    deadlineDate: new Date('2026-03-31'),
    location: 'Menlo Park, CA, USA',
    description: 'Build infrastructure that powers billions of connections across Meta\'s family of apps.',
    link: 'https://www.linkedin.com/jobs/view/software-engineer-intern-systems-infrastructure-phd-at-meta-4301047199',
    reward: '$10,000+/month Stipend',
    tags: ['Infrastructure', 'Scale', 'Social'],
  },

  // SCHOLARSHIPS (10)
  {
    id: 'schol-1',
    type: 'scholarship',
    title: 'Chevening Scholarship 2026/2027',
    organization: 'UK Government',
    deadline: 'Nov 5, 2025',
    deadlineDate: new Date('2025-11-05'),
    location: 'United Kingdom',
    description: 'Fully funded Master\'s degree in the UK covering tuition, living expenses, and travel.',
    link: 'https://www.chevening.org/apply/',
    reward: 'Full Tuition + Living Expenses',
    tags: ['Masters', 'UK', 'Leadership'],
  },
  {
    id: 'schol-2',
    type: 'scholarship',
    title: 'Gates Cambridge Scholarship 2026',
    organization: 'Gates Cambridge Trust',
    deadline: 'Oct 15, 2025',
    deadlineDate: new Date('2025-10-15'),
    location: 'Cambridge, UK',
    description: 'Full-cost scholarship for outstanding applicants to pursue postgraduate study at Cambridge.',
    link: 'https://www.gatescambridge.org/apply/',
    reward: 'Full Tuition + Stipend',
    tags: ['Postgrad', 'Cambridge', 'Research'],
  },
  {
    id: 'schol-3',
    type: 'scholarship',
    title: 'Rhodes Scholarship 2026',
    organization: 'Rhodes Trust',
    deadline: 'Jul 31, 2025',
    deadlineDate: new Date('2025-07-31'),
    location: 'Oxford, UK',
    description: 'The oldest and most prestigious international scholarship for study at University of Oxford.',
    link: 'https://www.rhodeshouse.ox.ac.uk/',
    reward: 'Full Tuition + Stipend + Travel',
    tags: ['Oxford', 'Leadership', 'Service'],
  },
  {
    id: 'schol-4',
    type: 'scholarship',
    title: 'Fulbright Foreign Student Program 2026',
    organization: 'US Department of State',
    deadline: 'Feb 28, 2026',
    deadlineDate: new Date('2026-02-28'),
    location: 'United States',
    description: 'Fully funded graduate study, research, or teaching assistantship in the United States.',
    link: 'https://foreign.fulbrightonline.org/',
    reward: 'Full Funding + J-1 Visa',
    tags: ['USA', 'Graduate', 'Research'],
  },
  {
    id: 'schol-5',
    type: 'scholarship',
    title: 'DAAD Scholarship 2026/2027',
    organization: 'German Academic Exchange Service',
    deadline: 'Oct 15, 2025',
    deadlineDate: new Date('2025-10-15'),
    location: 'Germany',
    description: 'Scholarships for Master\'s and PhD programs at German universities with monthly stipend.',
    link: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    reward: '€934/month + Tuition',
    tags: ['Germany', 'Masters', 'PhD'],
  },
  {
    id: 'schol-6',
    type: 'scholarship',
    title: 'Erasmus Mundus Joint Masters 2026',
    organization: 'European Union',
    deadline: 'Jan 15, 2026',
    deadlineDate: new Date('2026-01-15'),
    location: 'Europe (Multiple Countries)',
    description: 'Study at multiple European universities with full scholarship covering tuition and living costs.',
    link: 'https://erasmus-plus.ec.europa.eu/',
    reward: '€1,400/month + Full Tuition',
    tags: ['Europe', 'Masters', 'International'],
  },
  {
    id: 'schol-7',
    type: 'scholarship',
    title: 'Beacon Scholarship 2026',
    organization: 'Imperial College London',
    deadline: 'Feb 11, 2026',
    deadlineDate: new Date('2026-02-11'),
    location: 'London, UK',
    description: 'Fully funded scholarship for students from Africa pursuing STEM degrees at Imperial College.',
    link: 'https://www.imperial.ac.uk/',
    reward: 'Full Tuition + Living + Travel',
    tags: ['Africa', 'STEM', 'UK'],
  },
  {
    id: 'schol-8',
    type: 'scholarship',
    title: 'Gilman Scholarship 2026',
    organization: 'US Department of State',
    deadline: 'Mar 15, 2026',
    deadlineDate: new Date('2026-03-15'),
    location: 'Various Countries',
    description: 'Up to $5,000 for US undergraduates with financial need to study or intern abroad.',
    link: 'https://www.gilmanscholarship.org/',
    reward: 'Up to $5,000 Grant',
    tags: ['USA', 'Study Abroad', 'Undergraduate'],
  },
  {
    id: 'schol-9',
    type: 'scholarship',
    title: 'Google Africa Developer Scholarship 2026',
    organization: 'Google',
    deadline: 'Feb 28, 2026',
    deadlineDate: new Date('2026-02-28'),
    location: 'Africa (Online)',
    description: 'Free training in mobile and web development with Google certification upon completion.',
    link: 'https://developers.google.com/community/gdsc',
    reward: 'Free Training + Certification',
    isRemote: true,
    tags: ['Tech', 'Africa', 'Google'],
  },
  {
    id: 'schol-10',
    type: 'scholarship',
    title: 'ALX Software Engineering Program',
    organization: 'ALX Africa',
    deadline: 'Rolling Admissions',
    deadlineDate: new Date('2026-12-31'),
    location: 'Pan-African (Online)',
    description: '12-month intensive software engineering program with job placement support for African talent.',
    link: 'https://www.alxafrica.com/',
    reward: 'Free Training + Career Support',
    isRemote: true,
    tags: ['Africa', 'Software', 'Career'],
  },
];

export const getOpportunitiesByType = (type?: 'scholarship' | 'internship' | 'hackathon') => {
  if (!type) return opportunities;
  return opportunities.filter(opp => opp.type === type);
};

export const getUpcomingOpportunities = () => {
  const now = new Date();
  return opportunities
    .filter(opp => opp.deadlineDate >= now)
    .sort((a, b) => a.deadlineDate.getTime() - b.deadlineDate.getTime());
};

export const getOpportunityCounts = () => {
  return {
    all: opportunities.length,
    scholarships: opportunities.filter(o => o.type === 'scholarship').length,
    internships: opportunities.filter(o => o.type === 'internship').length,
    hackathons: opportunities.filter(o => o.type === 'hackathon').length,
  };
};
